posix_serialport_impl.c: error: incompatible pointer to integer
Clang 15 has enabled -Werror=int-conversion by default. Hence, we now get

posix_serialport_impl.c:113:13: error: incompatible pointer to integer
conversion passing 'struct RFile *' to parameter of type 'VALUE'
(aka 'unsigned long') [-Wint-conversion]
OBJSETUP(sp, class, T_FILE);
^~
This commit should fix this build error.

Bug: https://bugs.gentoo.org/883127
Signed-off-by: Brahmajit Das <brahmajit.xyz@gmail.com>